apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: using-build-and-deploy-
  namespace: lsnidero-sandbox
spec:
  pipelineRef:
    name: build-and-deploy
  workspaces:
  - name: build-workspace
    persistentVolumeClaim:
      claimName: shared-task-storage
  params:
  - name: repo-url
    value: https://github.com/lsnidero/ci.docker.websphere-traditional
  - name: branch-name
    value: master
  - name: repo-context
    value: samples/hello-world
  - name: repo-dockerfile
    value: Dockerfile.ubi
  - name: image-url
    value: image-registry.openshift-image-registry.svc:5000/lsnidero-sandbox/sample:latest
